name: java ci with maven
on:
  push:
    branches: [main]

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: build java packege
      run: maven clean install -f Javarepo1/pom.xml
 
